### ISSUE TITLE
Introduce a feature that allows users to more easily copy their selected option in `select` & `multiselect`  fields

### ISSUE THREAD

**Issue by ooaklee** [boasiHQ/interactive-inputs#1]
## SUMMARY

In our current version, it's relatively tricky for users to copy the value for their selection for the [`select`](https://github.com/boasiHQ/interactive-inputs/?tab=readme-ov-file#select-input---select) and [`multiselect`](https://github.com/boasiHQ/interactive-inputs/?tab=readme-ov-file#multi-select-input---multiselect) type fields without inspecting the HTML and pulling the value from the component. This is a relatively bad user experience. 

Update the portal logic, allowing users to auto-copy their selected option's value to the clipboard and make it the default behaviour. It should also be easy to disable this and return to the original behaviour if a user so desires. 

When configuring the auto copy to clipboard, we would expect to be able to do it at the property level of the field(s), i.e.: 

```yaml
fields:
 - label: countries-to-rate-limit
    properties:
      display: Which countries should have a limited request rate?
      type: multiselect
      disableAutoCopySelection: true
      choices: 
        - US
        - UK
```

```yaml
fields:
 - label: countries-to-rate-limit
    properties:
      display: Which countries should have a limited request rate?
      type: select
      disableAutoCopySelection: false # Default option
      choices: 
        - US
        - UK
```

> Note the additional property `disableAutoCopySelection`

## SUCCESS CRITERIA

- Add an additional property to the `select` & `multiselect` fields that allow users to enable and disable auto-copying of their selection easily
  - This property will be called `disableAutoCopySelection`
- Update README documentation to reflect changes added
